%% Spin Bath
spin_bath_parameter=containers.Map(...
    {'method', 'cut_off'},...
    {'random', 500}...
    );
%% CCE
cce_parameter=containers.Map(...
    {'max_order'},...
    {4}...
    );
%% Root
parameter_dict=containers.Map(...
    {'SpinBath', 'CCE'},...
    {spin_bath_parameter, cce_parameter}, ...
    'UniformValues', 0);

%% Export
path2file='/Users/nzhao/code/lib/active/qlib/+controller/+xml/';
xml_file= [path2file, 'config.xml.example'];
controller.xml.dict2xml(parameter_dict, xml_file);

disp(xml_file);
type(xml_file)