%% Spin Chain: Direct evolution and compare with GPU
% Need input file 'SpinChain.xml' in the folder specified by INPUT_FILE_PATH
% Need input file 'Res_iFILE_Data_SpinChain.dat' generated by GPU

% Output file 'Data_SpinChain.dat' with date and time tag
% in the folder specified by OUTPUT_FILE_PATH

%% Direct evolution
sol=model.phy.Solution.SpinChain('SpinChain.xml');
sol.perform();

%% Load GPU result and calculate Mean value
sol.LoadFromGPU([OUTPUT_FILE_PATH, 'Res_iFILE_Data_SpinChain.dat']);

obsMat=sol.result.observables{1}.matrix;
gpu_res=sol.result.GPU_Result;
GPU_MeanValue=sum(conj(gpu_res).* (obsMat*gpu_res));


%% comparison
tlist=sol.parameters.TimeList;
matlab_MeanValue=sol.result.mean_values('sz1');
plot(tlist, GPU_MeanValue, 'r*-', tlist, matlab_MeanValue, 'bo');